### ISSUE TITLE
Sends a barrage of requests when failing to load a weird .heic image

### ISSUE THREAD

**Issue by voidlynx** [zamfofex/jxl-crx#8]
I'm seriously not sure how to replicate this. I took an image on my phone, posted it to cohost, and it fails to load properly on Firefox. Checked my network log - a barrage of requests were sent, as seen on the image below:

![image](https://github.com/zamfofex/jxl-crx/assets/59738161/603ad8d0-f8c4-4b5f-be1b-6140589c65d8)

After checking the console log, it seems that it was indeed the line 27 in `worker.js` of this extension throwing the error. Disabling the extension stops the request barrage. Image still doesn't load though, not sure why.

This can be replicated, as of now, by going on this page: https://cohost.org/reth/post/3098559-it-has-arrived

**Comment by zamfofex** [comment]
I will note that I’m not actively working on this extension anymore, but I’m happy to review pull requests and submit a new version to the respective web extension stores! (If anyone is willing to contribute.)

**Comment by rkolka** [comment]
Same here. Endless loop of requests like https://res.cloudinary.com/cloudinary-marketing/images/c_fill,w_200/f_auto,q_auto/v1663977472/Cld_Blog_FeatImg_Sept2k22_Collage_Technically/Cld_Blog_FeatImg_Sept2k22_Collage_Technically-png?_i=AA   

On  cloudinary.com/blog/the-case-for-jpeg-xl  of all the places.

Uncaught TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'.
    at lazy-load-code-widget.js?ver=d3cb7cd923f91f587c311c91097eeb81:1:284


worker.js:27  Uncaught (in promise) Error: could not process input
    at error (worker.js:27:9)
    at loadJPEGXL (worker.js:58:4)
    at worker.js:10:42

worker.js:27  Uncaught (in promise)  keeps repeating endlessly

**Comment by zamfofex** [comment]
Is this a duplicate of #4?
